Fixing a problem while reading the plan (#494) (#497)
* Fixing a problem while reading the plan (#494)

If a state file contains "child_modules", below error is thrown.
So this commit will handle the case of supporting child modules.

ERROR: state.out.json is not a valid terraform plan json output.

* Update terraform_compliance/common/readable_plan.py

Co-authored-by: Emre Erkunt <emre.erkunt@gmail.com>

* Update tests/functional/test_child_modules/main.tf

Co-authored-by: Emre Erkunt <emre.erkunt@gmail.com>

Co-authored-by: Praveen Shilavantar <praveenshilavantar@Praveens-MacBook-Pro.local>
Co-authored-by: Emre Erkunt <emre.erkunt@gmail.com>