Fixing a problem while reading the plan (#494)
If a state file contains "child_modules", below error is thrown.
So this commit will handle the case of supporting child modules.

ERROR: state.out.json is not a valid terraform plan json output.